version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn test

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
